[package]
name = "rsvcs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
sha1 = "0.10"  # or use sha2 for sha256
walkdir = "2"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4" 
